##################################
# Check requirements before insall
##################################
- name: Ensure dependancies presence's
  apt:
    name:
      - curl
      - unzip
    state: present